/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package examen2p2_jorgerush;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import static javax.swing.JFileChooser.APPROVE_OPTION;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.MutableTreeNode;

/**
 *
 * @author Jorge Rush
 */
public class Main extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Main.class.getName());

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        DefaultComboBoxModel modeloCombo = new DefaultComboBoxModel();
        ComboLuchadores.setModel(modeloCombo);
        luchador1.setModel(modeloCombo);
        luchador2.setModel(modeloCombo);
        

        ocultarPantallas(false);
        DefaultMutableTreeNode reino = new DefaultMutableTreeNode("Reinos");

        DefaultTreeModel modeloArbol = new DefaultTreeModel(reino);
        arbolReinos.setModel(modeloArbol);
    }

    public void ocultarPantallas(boolean mostrar) {
        CrearHabilidad.setVisible(mostrar);
        Torneo.setVisible(mostrar);
        Versus.setVisible(mostrar);
        VerReino.setVisible(mostrar);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Torneo = new javax.swing.JPanel();
        Versus = new javax.swing.JPanel();
        luchador1 = new javax.swing.JComboBox<>();
        luchador2 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        golpe = new javax.swing.JButton();
        golpe2 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        mostrar = new javax.swing.JPanel();
        Jugador1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        combo2 = new javax.swing.JComboBox<>();
        h2 = new javax.swing.JButton();
        combo1 = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        Jugador2 = new javax.swing.JPanel();
        h1 = new javax.swing.JButton();
        VerReino = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        arbolReinos = new javax.swing.JTree();
        jScrollPane2 = new javax.swing.JScrollPane();
        verInfo = new javax.swing.JTextArea();
        jButton7 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        CrearHabilidad = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        ComboLuchadores = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        daño = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        comboEstado = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Torneo.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout TorneoLayout = new javax.swing.GroupLayout(Torneo);
        Torneo.setLayout(TorneoLayout);
        TorneoLayout.setHorizontalGroup(
            TorneoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );
        TorneoLayout.setVerticalGroup(
            TorneoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
        );

        jPanel1.add(Torneo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 540, 580));

        Versus.setBackground(new java.awt.Color(255, 255, 255));
        Versus.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        luchador1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Versus.add(luchador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 60, 134, -1));

        luchador2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Versus.add(luchador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, 134, -1));

        jLabel7.setText("Luchador 1");
        Versus.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 32, -1, -1));

        jLabel8.setText("Luchador 2");
        Versus.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(316, 32, -1, -1));

        jButton8.setText("Fijar Luchadores");
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton8MouseClicked(evt);
            }
        });
        Versus.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 121, -1, -1));

        golpe.setText("Golpe");
        Versus.add(golpe, new org.netbeans.lib.awtextra.AbsoluteConstraints(377, 227, -1, -1));

        golpe2.setText("Golpe");
        Versus.add(golpe2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, -1, -1));

        jLabel11.setText("Habilidades");
        Versus.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 304, -1, -1));

        jLabel12.setText("Habilidades");
        Versus.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(387, 304, -1, -1));

        mostrar.setBackground(new java.awt.Color(255, 255, 255));
        mostrar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setText("Vida:");

        combo2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        h2.setText("Usar Habilidad");

        javax.swing.GroupLayout Jugador1Layout = new javax.swing.GroupLayout(Jugador1);
        Jugador1.setLayout(Jugador1Layout);
        Jugador1Layout.setHorizontalGroup(
            Jugador1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Jugador1Layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(Jugador1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Jugador1Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Jugador1Layout.createSequentialGroup()
                        .addComponent(combo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Jugador1Layout.createSequentialGroup()
                        .addComponent(h2)
                        .addGap(23, 23, 23))))
        );
        Jugador1Layout.setVerticalGroup(
            Jugador1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Jugador1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)
                .addComponent(combo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(h2)
                .addGap(43, 43, 43))
        );

        mostrar.add(Jugador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 170, 280));

        combo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        mostrar.add(combo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 180, -1, -1));

        jLabel10.setText("Vida:");
        mostrar.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 40, -1, -1));

        h1.setText("Usar Habilidad");

        javax.swing.GroupLayout Jugador2Layout = new javax.swing.GroupLayout(Jugador2);
        Jugador2.setLayout(Jugador2Layout);
        Jugador2Layout.setHorizontalGroup(
            Jugador2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Jugador2Layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(h1)
                .addGap(26, 26, 26))
        );
        Jugador2Layout.setVerticalGroup(
            Jugador2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Jugador2Layout.createSequentialGroup()
                .addContainerGap(218, Short.MAX_VALUE)
                .addComponent(h1)
                .addGap(39, 39, 39))
        );

        mostrar.add(Jugador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 170, 280));

        Versus.add(mostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 510, 310));

        jPanel1.add(Versus, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 540, 580));

        VerReino.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setText("Ver Reinos");

        arbolReinos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                arbolReinosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(arbolReinos);

        verInfo.setEditable(false);
        verInfo.setColumns(20);
        verInfo.setRows(5);
        jScrollPane2.setViewportView(verInfo);

        jButton7.setText("Ver");
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout VerReinoLayout = new javax.swing.GroupLayout(VerReino);
        VerReino.setLayout(VerReinoLayout);
        VerReinoLayout.setHorizontalGroup(
            VerReinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VerReinoLayout.createSequentialGroup()
                .addGroup(VerReinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(VerReinoLayout.createSequentialGroup()
                        .addGap(233, 233, 233)
                        .addComponent(jLabel6))
                    .addGroup(VerReinoLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(VerReinoLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jButton7)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        VerReinoLayout.setVerticalGroup(
            VerReinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VerReinoLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(VerReinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 451, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addGap(18, 18, 18)
                .addComponent(jButton7)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel1.add(VerReino, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 540, 580));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/examen2p2_jorgerush/logoMK-1.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 16, 249, -1));

        jButton1.setText("Torneo");
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, 230, -1));

        jButton2.setText("Leer Luchador");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 230, -1));

        jButton3.setText("Crear Habilidad");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jButton3.addActionListener(this::jButton3ActionPerformed);
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 230, -1));

        jButton4.setText("Ver Reino");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 230, -1));

        jButton5.setText("1vs1");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });
        jPanel2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 230, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 580));

        CrearHabilidad.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setText("Luchador");

        ComboLuchadores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setText("Nombre:");

        jLabel4.setText("Daño:");

        jLabel5.setText("Efecto:");

        jButton6.setText("Crear");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });

        comboEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Quemadura", "Congelado", "Arturdido" }));

        javax.swing.GroupLayout CrearHabilidadLayout = new javax.swing.GroupLayout(CrearHabilidad);
        CrearHabilidad.setLayout(CrearHabilidadLayout);
        CrearHabilidadLayout.setHorizontalGroup(
            CrearHabilidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CrearHabilidadLayout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addGroup(CrearHabilidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(CrearHabilidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ComboLuchadores, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nombre)
                    .addComponent(daño)
                    .addComponent(comboEstado, 0, 195, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(CrearHabilidadLayout.createSequentialGroup()
                .addGap(237, 237, 237)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CrearHabilidadLayout.createSequentialGroup()
                .addContainerGap(237, Short.MAX_VALUE)
                .addComponent(jButton6)
                .addGap(231, 231, 231))
        );
        CrearHabilidadLayout.setVerticalGroup(
            CrearHabilidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CrearHabilidadLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ComboLuchadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(CrearHabilidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CrearHabilidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(daño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CrearHabilidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(comboEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jButton6)
                .addContainerGap(279, Short.MAX_VALUE))
        );

        jPanel1.add(CrearHabilidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 540, 580));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents
ArrayList<Luchador> luchadores = new ArrayList<>();
    ArrayList<Reino> Reinos = new ArrayList<>();
    int contador = -1;
    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        JFileChooser archivo = new JFileChooser();
        int opcion = archivo.showOpenDialog(this);
        if (opcion == APPROVE_OPTION) {
            File Archivo = archivo.getSelectedFile();
            FileReader leerArchivo;
            try {
                leerArchivo = new FileReader(Archivo);
                BufferedReader lectura = new BufferedReader(leerArchivo);
                String linea = lectura.readLine();
                do {
                    String[] datos = linea.split(";");
                    double vida = Double.parseDouble(datos[2]);
                    double velocidad = Double.parseDouble(datos[4]);
                    double probabilidad = Double.parseDouble(datos[5]);
                    double bonoHabilidad = Double.parseDouble(datos[6]);
                    Luchador nuevoLuchador = new Luchador(datos[0], datos[1], vida, datos[3], velocidad, probabilidad, bonoHabilidad);
                    luchadores.add(nuevoLuchador);
                    DefaultComboBoxModel modeloCombo = (DefaultComboBoxModel) ComboLuchadores.getModel();
                    modeloCombo.addElement(nuevoLuchador);

                    boolean verfReino = false;

                    for (int i = 0; i < Reinos.size(); i++) {

                        if (Reinos.get(i).getNombre().equals(datos[0])) {

                            verfReino = true;
                            Reino reinoElegido = Reinos.get(i);
                            ArrayList<Luchador> luchadores = reinoElegido.getLuchadores();

                            boolean evitarRep = false;
                            for (int j = 0; j < luchadores.size(); j++) {
                                if (luchadores.get(j).getNombre().equals(nuevoLuchador.getNombre())) {
                                    evitarRep = true;
                                }

                            }

                            if (evitarRep == false) {
                                reinoElegido.añadirLuchadores(nuevoLuchador);

                                DefaultTreeModel modeloArbol = (DefaultTreeModel) arbolReinos.getModel();
                                DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) modeloArbol.getRoot();

                                DefaultMutableTreeNode nodoExistente = (DefaultMutableTreeNode) raiz.getChildAt(contador);
                                DefaultMutableTreeNode hijo = new DefaultMutableTreeNode(nuevoLuchador);
                                nodoExistente.add(hijo);
                            }

                        } else {
//                            Reino nuevoReino = new Reino(datos[0]);
//                            Reinos.add(nuevoReino);
//                            nuevoReino.añadirLuchadores(nuevoLuchador);
//                            DefaultTreeModel modeloArbol = (DefaultTreeModel) arbolReinos.getModel();
//                            DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) modeloArbol.getRoot();
//                            DefaultMutableTreeNode nuevoNodo = new DefaultMutableTreeNode(datos[0]);
//                            raiz.add(nuevoNodo);
//                            DefaultMutableTreeNode hijo = (DefaultMutableTreeNode) raiz.getChildAt(Reinos.size() - 1);
//                            nuevoNodo.add(hijo);
                        }
                    }
                    boolean reinoCreado = false;
                    if (verfReino == false) {
                        Reino nuevoReino = new Reino(datos[0]);
                        Reinos.add(nuevoReino);
                        contador++;

                        nuevoReino.añadirLuchadores(nuevoLuchador);
                        Reinos.add(nuevoReino);
                        System.out.println(nuevoReino.Nombre);
                        reinoCreado = true;

                    }
                    if (reinoCreado == true) {

                        DefaultTreeModel modeloArbol = (DefaultTreeModel) arbolReinos.getModel();
                        DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) modeloArbol.getRoot();
                        DefaultMutableTreeNode nuevoReino = new DefaultMutableTreeNode(datos[0]);
                        raiz.add(nuevoReino);
                        DefaultMutableTreeNode nuevoNodo = new DefaultMutableTreeNode(nuevoLuchador);
                        nuevoReino.add(nuevoNodo);
                    }

                    linea = lectura.readLine();
                } while (linea != null);
                JOptionPane.showMessageDialog(this, "Archivo exitosamente cargado al sistema :D");
            } catch (FileNotFoundException ex) {
                System.getLogger(Main.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            } catch (IOException ex) {
                System.getLogger(Main.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            }

        }
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        String nombreN = nombre.getText();
        String dañoN = daño.getText();
        if (nombreN.isEmpty() || dañoN.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No puede dejar nada en blanco");
            return;
        }

        double dañoF = Double.parseDouble(dañoN);
        String estado = (String) comboEstado.getSelectedItem();

        Object luchadorElegido = ComboLuchadores.getSelectedItem();
        if (luchadorElegido instanceof Luchador) {
            Habilidad nuevaHabilidad = new Habilidad(nombreN, dañoF, estado);
            Luchador luchador = (Luchador) luchadorElegido;
            luchador.añadirHabilidades(nuevaHabilidad);
            DefaultTreeModel modeloArbol = (DefaultTreeModel) arbolReinos.getModel();
            DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) modeloArbol.getRoot();

            int cantidad = raiz.getChildCount();
            for (int i = 0; i < cantidad; i++) {
                DefaultMutableTreeNode nodoExistente = (DefaultMutableTreeNode) raiz.getChildAt(i);
                int cantidadF = nodoExistente.getChildCount();
                for (int j = 0; j < cantidadF; j++) {
                    DefaultMutableTreeNode nodoLuchador = (DefaultMutableTreeNode) nodoExistente.getChildAt(j);
                    if (nodoLuchador.toString().equals(luchador.getNombre())) {
                        DefaultMutableTreeNode nodoHabilidad = new DefaultMutableTreeNode(nuevaHabilidad);
                        nodoLuchador.add(nodoHabilidad);
                    }

                }

            }
            JOptionPane.showMessageDialog(this, "Habilidad exitosamente añadida");
            return;
        }
    }//GEN-LAST:event_jButton6MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        ocultarPantallas(false);
        CrearHabilidad.setVisible(true);

    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        ocultarPantallas(false);
        VerReino.setVisible(true);
        DefaultTreeModel modeloArbol = (DefaultTreeModel) arbolReinos.getModel();
        modeloArbol.reload();
    }//GEN-LAST:event_jButton4MouseClicked

    private void arbolReinosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_arbolReinosMouseClicked


    }//GEN-LAST:event_arbolReinosMouseClicked

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
        DefaultMutableTreeNode nodoSeleccionado = (DefaultMutableTreeNode) arbolReinos.getSelectionPath().getLastPathComponent();
        Object eleccion = nodoSeleccionado.getUserObject();
        try {

            String verifReino = (String) eleccion;
            for (int i = 0; i < Reinos.size(); i++) {
                if (Reinos.get(i).getNombre().equals(verifReino)) {
                    verInfo.setText(Reinos.get(i).toString());
                }
            }

        } catch (Exception E) {
            if (eleccion instanceof Luchador) {
                Luchador luchaEleg = (Luchador) eleccion;
                verInfo.setText(luchaEleg.toString2());
            } else if (eleccion instanceof Habilidad) {
                Habilidad habiliEleg = (Habilidad) eleccion;
                verInfo.setText(habiliEleg.toString());

            }
        }
        if (eleccion instanceof Luchador) {
            Luchador luchaEleg = (Luchador) eleccion;
            verInfo.setText(luchaEleg.toString2());
        } else if (eleccion instanceof Habilidad) {
            Habilidad habiliEleg = (Habilidad) eleccion;
            verInfo.setText(habiliEleg.toString());

        }


    }//GEN-LAST:event_jButton7MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        ocultarPantallas(false);
        Versus.setVisible(true);
    }//GEN-LAST:event_jButton5MouseClicked
    public void Jugador1(boolean mostrar) {
        h1.setEnabled(mostrar);
        combo1.setEnabled(mostrar);
        golpe.setEnabled(mostrar);

    }

    public void Jugador2(boolean mostrar) {
        h2.setEnabled(mostrar);
        combo2.setEnabled(mostrar);
        golpe2.setEnabled(mostrar);
    }
    private void jButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseClicked
        Jugador1(false);
        Jugador2(false);
        Luchador luchador = (Luchador) luchador1.getSelectedItem();
        Luchador luchadorT = (Luchador) luchador2.getSelectedItem();
        if (luchador.getVelocidad() > luchadorT.getVelocidad()) {
            Jugador1(true);
            Jugador2(false);
        } else {
            Jugador1(false);
            Jugador2(true);
        }
    }//GEN-LAST:event_jButton8MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Main().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboLuchadores;
    private javax.swing.JPanel CrearHabilidad;
    private javax.swing.JPanel Jugador1;
    private javax.swing.JPanel Jugador2;
    private javax.swing.JPanel Torneo;
    private javax.swing.JPanel VerReino;
    private javax.swing.JPanel Versus;
    private javax.swing.JTree arbolReinos;
    private javax.swing.JComboBox<String> combo1;
    private javax.swing.JComboBox<String> combo2;
    private javax.swing.JComboBox<String> comboEstado;
    private javax.swing.JTextField daño;
    private javax.swing.JButton golpe;
    private javax.swing.JButton golpe2;
    private javax.swing.JButton h1;
    private javax.swing.JButton h2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> luchador1;
    private javax.swing.JComboBox<String> luchador2;
    private javax.swing.JPanel mostrar;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextArea verInfo;
    // End of variables declaration//GEN-END:variables
}
