/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package examen2p2_jorgerush;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import static javax.swing.JFileChooser.APPROVE_OPTION;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author Jorge Rush
 */
public class Main extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Main.class.getName());

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        DefaultComboBoxModel modeloCombo = new DefaultComboBoxModel();
        ComboLuchadores.setModel(modeloCombo);
        ocultarPantallas(false);
        DefaultMutableTreeNode reino = new DefaultMutableTreeNode("Reinos");
        DefaultMutableTreeNode Earthrealm = new DefaultMutableTreeNode("Earthrealm");
        DefaultMutableTreeNode Outworld = new DefaultMutableTreeNode("Outworld");
        DefaultMutableTreeNode Edenia = new DefaultMutableTreeNode("Edenia");
        DefaultMutableTreeNode Netherrealm = new DefaultMutableTreeNode("Netherrealm");
        reino.add(Earthrealm);
        reino.add(Outworld);
        reino.add(Edenia);
        reino.add(Netherrealm);
        DefaultTreeModel modeloArbol = new DefaultTreeModel(reino);
        arbolReinos.setModel(modeloArbol);
    }

    public void ocultarPantallas(boolean mostrar) {
        CrearHabilidad.setVisible(mostrar);
        Torneo.setVisible(mostrar);
        Versus.setVisible(mostrar);
        VerReino.setVisible(mostrar);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Torneo = new javax.swing.JPanel();
        Versus = new javax.swing.JPanel();
        VerReino = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        arbolReinos = new javax.swing.JTree();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton7 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        CrearHabilidad = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        ComboLuchadores = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        daño = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        comboEstado = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Torneo.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout TorneoLayout = new javax.swing.GroupLayout(Torneo);
        Torneo.setLayout(TorneoLayout);
        TorneoLayout.setHorizontalGroup(
            TorneoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );
        TorneoLayout.setVerticalGroup(
            TorneoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
        );

        jPanel1.add(Torneo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 540, 580));

        Versus.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout VersusLayout = new javax.swing.GroupLayout(Versus);
        Versus.setLayout(VersusLayout);
        VersusLayout.setHorizontalGroup(
            VersusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );
        VersusLayout.setVerticalGroup(
            VersusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
        );

        jPanel1.add(Versus, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 540, 580));

        VerReino.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setText("Ver Reinos");

        jScrollPane1.setViewportView(arbolReinos);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jButton7.setText("Ver");

        javax.swing.GroupLayout VerReinoLayout = new javax.swing.GroupLayout(VerReino);
        VerReino.setLayout(VerReinoLayout);
        VerReinoLayout.setHorizontalGroup(
            VerReinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VerReinoLayout.createSequentialGroup()
                .addGroup(VerReinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(VerReinoLayout.createSequentialGroup()
                        .addGap(233, 233, 233)
                        .addComponent(jLabel6))
                    .addGroup(VerReinoLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(VerReinoLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jButton7)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        VerReinoLayout.setVerticalGroup(
            VerReinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VerReinoLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(VerReinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 451, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addGap(18, 18, 18)
                .addComponent(jButton7)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel1.add(VerReino, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 540, 580));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/examen2p2_jorgerush/logoMK-1.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 16, 249, -1));

        jButton1.setText("Torneo");
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, 230, -1));

        jButton2.setText("Leer Luchador");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 230, -1));

        jButton3.setText("Crear Habilidad");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jButton3.addActionListener(this::jButton3ActionPerformed);
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 230, -1));

        jButton4.setText("Ver Reino");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 230, -1));

        jButton5.setText("1vs1");
        jPanel2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 230, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 580));

        CrearHabilidad.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setText("Luchador");

        ComboLuchadores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setText("Nombre:");

        jLabel4.setText("Daño:");

        jLabel5.setText("Efecto:");

        jButton6.setText("Crear");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });

        comboEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Quemadura", "Congelado", "Arturdido" }));

        javax.swing.GroupLayout CrearHabilidadLayout = new javax.swing.GroupLayout(CrearHabilidad);
        CrearHabilidad.setLayout(CrearHabilidadLayout);
        CrearHabilidadLayout.setHorizontalGroup(
            CrearHabilidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CrearHabilidadLayout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addGroup(CrearHabilidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(CrearHabilidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ComboLuchadores, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nombre)
                    .addComponent(daño)
                    .addComponent(comboEstado, 0, 195, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(CrearHabilidadLayout.createSequentialGroup()
                .addGap(237, 237, 237)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CrearHabilidadLayout.createSequentialGroup()
                .addContainerGap(237, Short.MAX_VALUE)
                .addComponent(jButton6)
                .addGap(231, 231, 231))
        );
        CrearHabilidadLayout.setVerticalGroup(
            CrearHabilidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CrearHabilidadLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ComboLuchadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(CrearHabilidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CrearHabilidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(daño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CrearHabilidadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(comboEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jButton6)
                .addContainerGap(279, Short.MAX_VALUE))
        );

        jPanel1.add(CrearHabilidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 540, 580));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents
ArrayList<Luchador> luchadores = new ArrayList<>();
    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        JFileChooser archivo = new JFileChooser();
        int opcion = archivo.showOpenDialog(this);
        if (opcion == APPROVE_OPTION) {
            File Archivo = archivo.getSelectedFile();
            FileReader leerArchivo;
            try {
                leerArchivo = new FileReader(Archivo);
                BufferedReader lectura = new BufferedReader(leerArchivo);
                String linea = lectura.readLine();
                do {
                    String[] datos = linea.split(";");
                    double vida = Double.parseDouble(datos[2]);
                    double velocidad = Double.parseDouble(datos[4]);
                    double probabilidad = Double.parseDouble(datos[5]);
                    double bonoHabilidad = Double.parseDouble(datos[6]);
                    Luchador nuevoLuchador = new Luchador(datos[0], datos[1], vida, datos[3], velocidad, probabilidad, bonoHabilidad);
                    luchadores.add(nuevoLuchador);
                    DefaultComboBoxModel modeloCombo = (DefaultComboBoxModel) ComboLuchadores.getModel();
                    modeloCombo.addElement(nuevoLuchador);
                    DefaultTreeModel modeloArbol = (DefaultTreeModel) arbolReinos.getModel();
                    DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) modeloArbol.getRoot();
                    if (datos[0].equals("Earthrealm")) {
                        DefaultMutableTreeNode hijo = (DefaultMutableTreeNode) raiz.getChildAt(0);
                        DefaultMutableTreeNode nuevoNodo = new DefaultMutableTreeNode(nuevoLuchador);
                        hijo.add(nuevoNodo);
                    } else if (datos[0].equals("Outworld")) {
                        DefaultMutableTreeNode hijo = (DefaultMutableTreeNode) raiz.getChildAt(1);
                        DefaultMutableTreeNode nuevoNodo = new DefaultMutableTreeNode(nuevoLuchador);
                        hijo.add(nuevoNodo);
                    } else if (datos[0].equals("Edenia")) {
                        DefaultMutableTreeNode hijo = (DefaultMutableTreeNode) raiz.getChildAt(2);
                        DefaultMutableTreeNode nuevoNodo = new DefaultMutableTreeNode(nuevoLuchador);
                        hijo.add(nuevoNodo);
                    } else if (datos[0].equals("Netherrealm")) {
                        DefaultMutableTreeNode hijo = (DefaultMutableTreeNode) raiz.getChildAt(3);
                        DefaultMutableTreeNode nuevoNodo = new DefaultMutableTreeNode(nuevoLuchador);
                        hijo.add(nuevoNodo);
                    }
                    linea = lectura.readLine();
                } while (linea != null);
            } catch (FileNotFoundException ex) {
                System.getLogger(Main.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            } catch (IOException ex) {
                System.getLogger(Main.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            }

        }
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        String nombreN = nombre.getText();
        String dañoN = daño.getText();
        if (nombreN.isEmpty() || dañoN.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No puede dejar nada en blanco");
            return;
        }

        double dañoF = Double.parseDouble(dañoN);
        String estado = (String) comboEstado.getSelectedItem();

        Object luchadorElegido = ComboLuchadores.getSelectedItem();
        if (luchadorElegido instanceof Luchador) {
            Habilidad nuevaHabilidad = new Habilidad(nombreN, dañoF, estado);
            Luchador luchador = (Luchador) luchadorElegido;
            luchador.añadirHabilidades(nuevaHabilidad);
            JOptionPane.showMessageDialog(this, "Habilidad exitosamente añadida");
            return;
        }
    }//GEN-LAST:event_jButton6MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        ocultarPantallas(false);
        CrearHabilidad.setVisible(true);

    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        ocultarPantallas(false);
        VerReino.setVisible(true);
    }//GEN-LAST:event_jButton4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Main().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboLuchadores;
    private javax.swing.JPanel CrearHabilidad;
    private javax.swing.JPanel Torneo;
    private javax.swing.JPanel VerReino;
    private javax.swing.JPanel Versus;
    private javax.swing.JTree arbolReinos;
    private javax.swing.JComboBox<String> comboEstado;
    private javax.swing.JTextField daño;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField nombre;
    // End of variables declaration//GEN-END:variables
}
